faq_data_filtered = [
    {"id": "1", "category": "계정/보안", "text": "Question: 비밀번호를 잊어버렸습니다. 어떻게 재설정하나요?, Answer: 로그인 페이지에서 비밀번호 찾기를 클릭하고 가입 이메일로 재설정 링크를 받으세요."},
    {"id": "2", "category": "계정/보안", "text": "Question: 회원가입은 어떻게 하나요?, Answer: 이메일과 비밀번호를 입력하고 인증 메일을 확인하면 가입이 완료됩니다."},
    {"id": "3", "category": "계정/보안", "text": "Question: 이메일 인증이 오지 않습니다., Answer: 스팸함을 확인하거나 이메일 주소를 다시 확인해 주세요."},
    {"id": "4", "category": "계정/보안", "text": "Question: 로그인이 안 됩니다., Answer: 아이디와 비밀번호를 확인하고 비밀번호 재설정을 시도해 주세요."},
    {"id": "5", "category": "계정/보안", "text": "Question: 계정을 삭제하려면 어떻게 하나요?, Answer: 설정 메뉴에서 계정 삭제 요청을 진행할 수 있습니다."},
    {"id": "6", "category": "결제/구독", "text": "Question: 결제 수단을 변경하려면?, Answer: 결제 설정에서 카드 또는 계좌 정보를 수정할 수 있습니다."},
    {"id": "7", "category": "결제/구독", "text": "Question: 환불은 어떻게 받나요?, Answer: 구매 후 7일 이내 고객센터를 통해 환불 신청이 가능합니다."},
    {"id": "8", "category": "결제/구독", "text": "Question: 구독 해지는 어디서 하나요?, Answer: 계정 > 구독 관리 메뉴에서 해지할 수 있습니다."},
    {"id": "9", "category": "계정/보안", "text": "Question: 비밀번호 변경 방법은?, Answer: 계정 설정에서 현재 비밀번호 입력 후 새 비밀번호로 변경하세요."},
    {"id": "10", "category": "계정/보안", "text": "Question: 2단계 인증 설정 방법은?, Answer: 보안 설정에서 2단계 인증을 활성화하세요."},

    {"id": "11", "category": "앱/설정", "text": "Question: 앱이 실행되지 않습니다., Answer: 최신 버전으로 업데이트 후 재시도하세요."},
    {"id": "12", "category": "결제/구독", "text": "Question: 결제가 실패합니다., Answer: 카드 한도 또는 유효기간을 확인하세요."},
    {"id": "13", "category": "주문/배송", "text": "Question: 주문 내역은 어디서 보나요?, Answer: 마이페이지 주문 내역에서 확인 가능합니다."},
    {"id": "14", "category": "주문/배송", "text": "Question: 배송 상태는 어떻게 확인하나요?, Answer: 주문 상세 페이지에서 배송 추적이 가능합니다."},
    {"id": "15", "category": "주문/배송", "text": "Question: 배송 주소 변경 가능한가요?, Answer: 배송 시작 전까지 주소 변경이 가능합니다."},
    {"id": "16", "category": "결제/구독", "text": "Question: 쿠폰은 어떻게 사용하나요?, Answer: 결제 단계에서 쿠폰 코드를 입력하세요."},
    {"id": "17", "category": "결제/구독", "text": "Question: 포인트는 어떻게 적립되나요?, Answer: 구매 금액의 일정 비율로 자동 적립됩니다."},
    {"id": "18", "category": "결제/구독", "text": "Question: 포인트 사용 방법은?, Answer: 결제 시 포인트 사용 옵션을 선택하세요."},
    {"id": "19", "category": "고객센터", "text": "Question: 고객센터 연락 방법은?, Answer: 앱 내 고객센터 또는 이메일로 문의 가능합니다."},
    {"id": "20", "category": "고객센터", "text": "Question: 서비스 이용 시간은?, Answer: 24시간 이용 가능합니다."},

    {"id": "21", "category": "계정/보안", "text": "Question: 계정이 잠겼습니다., Answer: 비밀번호 재설정 후 잠금이 해제됩니다."},
    {"id": "22", "category": "계정/보안", "text": "Question: 이메일 변경은 어떻게 하나요?, Answer: 계정 설정에서 이메일 변경이 가능합니다."},
    {"id": "23", "category": "앱/설정", "text": "Question: 알림을 끄려면?, Answer: 설정 > 알림 메뉴에서 비활성화하세요."},
    {"id": "24", "category": "앱/설정", "text": "Question: 데이터 백업 방법은?, Answer: 설정에서 백업 기능을 활성화하세요."},
    {"id": "25", "category": "앱/설정", "text": "Question: 데이터 복구는 가능한가요?, Answer: 최근 백업 데이터를 통해 복구 가능합니다."},

    {"id": "26", "category": "앱/설정", "text": "Question: 앱 언어 변경은?, Answer: 설정 > 언어에서 변경 가능합니다."},
    {"id": "27", "category": "앱/설정", "text": "Question: 다크모드 설정 방법은?, Answer: 디스플레이 설정에서 다크모드를 선택하세요."},
    {"id": "28", "category": "계정/보안", "text": "Question: 로그아웃은 어디서 하나요?, Answer: 프로필 메뉴에서 로그아웃 가능합니다."},
    {"id": "29", "category": "앱/설정", "text": "Question: 여러 기기에서 사용 가능한가요?, Answer: 동일 계정으로 여러 기기에서 로그인 가능합니다."},
    {"id": "30", "category": "계정/보안", "text": "Question: 보안 로그 확인 방법은?, Answer: 보안 설정에서 로그인 기록을 확인하세요."},

    {"id": "31", "category": "결제/구독", "text": "Question: 결제 영수증은 어디서 받나요?, Answer: 이메일로 자동 발송됩니다."},
    {"id": "32", "category": "결제/구독", "text": "Question: 세금계산서 발급 가능한가요?, Answer: 고객센터 요청 시 발급 가능합니다."},
    {"id": "33", "category": "고객센터", "text": "Question: 서비스 장애 시 어떻게 하나요?, Answer: 공지사항을 확인하세요."},
    {"id": "34", "category": "개발/비즈니스", "text": "Question: API 사용 방법은?, Answer: 개발자 문서를 참고하세요."},
    {"id": "35", "category": "개발/비즈니스", "text": "Question: API 키는 어디서 발급하나요?, Answer: 개발자 설정 메뉴에서 발급 가능합니다."},

    {"id": "36", "category": "계정/보안", "text": "Question: 비밀번호 정책은?, Answer: 8자 이상 영문, 숫자 포함입니다."},
    {"id": "37", "category": "계정/보안", "text": "Question: 계정 복구 방법은?, Answer: 본인 인증 후 복구 가능합니다."},
    {"id": "38", "category": "계정/보안", "text": "Question: 탈퇴 후 재가입 가능한가요?, Answer: 가능합니다."},
    {"id": "39", "category": "결제/구독", "text": "Question: 광고 제거 방법은?, Answer: 프리미엄 구독 시 제거됩니다."},
    {"id": "40", "category": "결제/구독", "text": "Question: 프리미엄 기능은 무엇인가요?, Answer: 추가 기능 및 광고 제거가 포함됩니다."},

    {"id": "41", "category": "앱/설정", "text": "Question: 파일 업로드 제한은?, Answer: 최대 100MB까지 가능합니다."},
    {"id": "42", "category": "앱/설정", "text": "Question: 업로드가 실패합니다., Answer: 네트워크 상태를 확인하세요."},
    {"id": "43", "category": "앱/설정", "text": "Question: 다운로드 속도가 느립니다., Answer: 네트워크 환경을 확인하세요."},
    {"id": "44", "category": "앱/설정", "text": "Question: 캐시 삭제 방법은?, Answer: 설정에서 캐시 삭제 가능합니다."},
    {"id": "45", "category": "앱/설정", "text": "Question: 앱 충돌이 발생합니다., Answer: 최신 버전으로 업데이트하세요."},

    {"id": "46", "category": "계정/보안", "text": "Question: 로그인 기록은 어디서 보나요?, Answer: 보안 설정에서 확인 가능합니다."},
    {"id": "47", "category": "계정/보안", "text": "Question: 의심 로그인 알림이 왔습니다., Answer: 즉시 비밀번호를 변경하세요."},
    {"id": "48", "category": "계정/보안", "text": "Question: 자동 로그인을 끄려면?, Answer: 로그인 설정에서 해제하세요."},
    {"id": "49", "category": "앱/설정", "text": "Question: 계정 동기화 방법은?, Answer: 동일 계정으로 로그인하면 자동 동기화됩니다."},
    {"id": "50", "category": "계정/보안", "text": "Question: 로그인이 자주 풀립니다., Answer: 쿠키 설정을 확인하세요."},

    {"id": "51", "category": "앱/설정", "text": "Question: 모바일에서도 사용 가능한가요?, Answer: 모바일 앱을 통해 사용 가능합니다."},
    {"id": "52", "category": "앱/설정", "text": "Question: PC와 모바일 동기화 되나요?, Answer: 동일 계정으로 자동 동기화됩니다."},
    {"id": "53", "category": "앱/설정", "text": "Question: 브라우저 지원은?, Answer: 최신 Chrome, Edge 지원합니다."},
    {"id": "54", "category": "고객센터", "text": "Question: 시스템 점검 시간은?, Answer: 공지사항에서 확인 가능합니다."},
    {"id": "55", "category": "고객센터", "text": "Question: 점검 중 이용 가능한가요?, Answer: 일부 기능 제한됩니다."},

    {"id": "56", "category": "이벤트/혜택", "text": "Question: 회원 등급은 어떻게 나뉘나요?, Answer: 이용 실적에 따라 나뉩니다."},
    {"id": "57", "category": "이벤트/혜택", "text": "Question: 등급 혜택은?, Answer: 할인 및 포인트 혜택이 있습니다."},
    {"id": "58", "category": "이벤트/혜택", "text": "Question: 친구 초대는 어떻게 하나요?, Answer: 초대 링크를 공유하세요."},
    {"id": "59", "category": "이벤트/혜택", "text": "Question: 추천 보상은?, Answer: 초대 성공 시 포인트 지급됩니다."},
    {"id": "60", "category": "이벤트/혜택", "text": "Question: 이벤트는 어디서 확인하나요?, Answer: 이벤트 페이지에서 확인 가능합니다."},

    {"id": "61", "category": "이벤트/혜택", "text": "Question: 이벤트 참여 방법은?, Answer: 이벤트 페이지에서 참여 버튼을 누르세요."},
    {"id": "62", "category": "이벤트/혜택", "text": "Question: 이벤트 당첨 확인은?, Answer: 공지사항에서 확인 가능합니다."},
    {"id": "63", "category": "이벤트/혜택", "text": "Question: 쿠폰 유효기간은?, Answer: 발급일 기준으로 정해집니다."},
    {"id": "64", "category": "이벤트/혜택", "text": "Question: 쿠폰 중복 사용 가능한가요?, Answer: 불가능합니다."},
    {"id": "65", "category": "결제/구독", "text": "Question: 결제 취소는 언제까지 가능한가요?, Answer: 결제 후 7일 이내 가능합니다."},

    {"id": "66", "category": "결제/구독", "text": "Question: 환불 소요 시간은?, Answer: 3~5일 정도 소요됩니다."},
    {"id": "67", "category": "결제/구독", "text": "Question: 부분 환불 가능한가요?, Answer: 상품에 따라 다릅니다."},
    {"id": "68", "category": "고객센터", "text": "Question: 고객센터 운영 시간은?, Answer: 평일 9시~18시입니다."},
    {"id": "69", "category": "고객센터", "text": "Question: 상담 대기 시간이 길어요., Answer: 문의량에 따라 달라집니다."},
    {"id": "70", "category": "고객센터", "text": "Question: 챗봇이 있나요?, Answer: 24시간 자동 응답 챗봇이 있습니다."},

    {"id": "71", "category": "계정/보안", "text": "Question: 데이터 삭제 요청 방법은?, Answer: 설정에서 요청 가능합니다."},
    {"id": "72", "category": "계정/보안", "text": "Question: 개인정보 보호는 어떻게 되나요?, Answer: 암호화되어 안전하게 저장됩니다."},
    {"id": "73", "category": "계정/보안", "text": "Question: 로그 데이터는 저장되나요?, Answer: 보안 목적상 일부 저장됩니다."},
    {"id": "74", "category": "고객센터", "text": "Question: 서비스 약관은 어디서 보나요?, Answer: 설정 메뉴에서 확인 가능합니다."},
    {"id": "75", "category": "계정/보안", "text": "Question: 개인정보 수정은?, Answer: 계정 설정에서 가능합니다."},

    {"id": "76", "category": "앱/설정", "text": "Question: 앱 설치가 안 됩니다., Answer: 저장 공간을 확인하세요."},
    {"id": "77", "category": "앱/설정", "text": "Question: 업데이트 방법은?, Answer: 앱스토어에서 업데이트 가능합니다."},
    {"id": "78", "category": "앱/설정", "text": "Question: 자동 업데이트 설정은?, Answer: 설정에서 활성화 가능합니다."},
    {"id": "79", "category": "앱/설정", "text": "Question: 오류 코드 404는?, Answer: 페이지가 존재하지 않습니다."},
    {"id": "80", "category": "앱/설정", "text": "Question: 오류 코드 500은?, Answer: 서버 내부 오류입니다."},

    {"id": "81", "category": "개발/비즈니스", "text": "Question: API 속도 제한은?, Answer: 초당 요청 제한이 있습니다."},
    {"id": "82", "category": "개발/비즈니스", "text": "Question: API 문서는 어디 있나요?, Answer: 개발자 포털에서 확인 가능합니다."},
    {"id": "83", "category": "개발/비즈니스", "text": "Question: SDK 지원 언어는?, Answer: Python, Java, JS를 지원합니다."},
    {"id": "84", "category": "개발/비즈니스", "text": "Question: Webhook 설정은?, Answer: 개발자 설정에서 가능합니다."},
    {"id": "85", "category": "개발/비즈니스", "text": "Question: 실시간 알림 지원하나요?, Answer: WebSocket 또는 webhook으로 지원합니다."},

    {"id": "86", "category": "개발/비즈니스", "text": "Question: 데이터 동기화 주기는?, Answer: 실시간 또는 5분 단위입니다."},
    {"id": "87", "category": "개발/비즈니스", "text": "Question: 백업 주기는?, Answer: 하루 1회 자동 백업됩니다."},
    {"id": "88", "category": "개발/비즈니스", "text": "Question: 서버 위치는?, Answer: AWS 리전 기반입니다."},
    {"id": "89", "category": "개발/비즈니스", "text": "Question: 데이터 암호화 방식은?, Answer: AES-256을 사용합니다."},
    {"id": "90", "category": "계정/보안", "text": "Question: 로그인 보안 강화 방법은?, Answer: 2FA 설정을 권장합니다."},

    {"id": "91", "category": "계정/보안", "text": "Question: 계정 해킹 의심 시?, Answer: 즉시 비밀번호 변경하세요."},
    {"id": "92", "category": "계정/보안", "text": "Question: IP 제한 가능한가요?, Answer: 관리자 기능에서 설정 가능합니다."},
    {"id": "93", "category": "계정/보안", "text": "Question: 접근 로그 확인 방법은?, Answer: 보안 메뉴에서 확인 가능합니다."},
    {"id": "94", "category": "개발/비즈니스", "text": "Question: 사용자 권한 관리 방법은?, Answer: 관리자 설정에서 가능합니다."},
    {"id": "95", "category": "개발/비즈니스", "text": "Question: 팀 계정 지원하나요?, Answer: 엔터프라이즈 플랜에서 지원합니다."},

    {"id": "96", "category": "개발/비즈니스", "text": "Question: 협업 기능 있나요?, Answer: 팀 워크스페이스를 제공합니다."},
    {"id": "97", "category": "개발/비즈니스", "text": "Question: 파일 공유 방법은?, Answer: 링크 공유 기능을 사용하세요."},
    {"id": "98", "category": "개발/비즈니스", "text": "Question: 외부 공유 제한 가능한가요?, Answer: 관리자 설정에서 가능합니다."},
    {"id": "99", "category": "개발/비즈니스", "text": "Question: 알림 설정 세부 조정 가능한가요?, Answer: 이벤트별로 설정 가능합니다."},
    {"id": "100", "category": "고객센터", "text": "Question: 서비스 전체 상태는 어디서 보나요?, Answer: 상태 페이지에서 확인 가능합니다."}
]